---
title: "Fast maximal cliques enumeration by locally optimal vertex ordering"
author: Yulong Niu
date: "`r Sys.Date()`"
csl: nature.csl
bibliography: MaximalCliqueRef.bib
header-includes:
  - \usepackage{amsmath}
  - \usepackage{mathtools}
output:
  BiocStyle::html_document:
    toc: true
    toc_float: true
  BiocStyle::pdf_document:
    toc: true
    latex_engine: pdflatex
vignette: |
  %\VignetteIndexEntry{Global ETF}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r style, echo=FALSE, results='asis', message=FALSE}
options(tinytex.verbose = TRUE)
BiocStyle::markdown()
knitr::opts_chunk$set(tidy = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

# Algorithm

## Preliminaries

* A simple undirected graph is denoted as $G(V, E)$, $V$ are vertices and $E$ are edges.

* For a vertex $v \in V$, $\Gamma(v)$ denotes all vertices adjacent to $v$ in $G$. Note that $v \notin \Gamma(v)$.

## Algorithm design

The algorithm described here is used for fast maximal cliques enumeration (MCE) of undirected graphs. Most optimizations are attributed to "locally optimal vertex ordering", so we named the new algorithm as "`LOVO`".

`LOVO`, inspired by Bron-Kerbosch's algorithm [@bron1973algorithm], operated three disjoint sets of vertices during the search for maximal cliques:

$X$: $x \in X$ are searched vertices. Maximal cliques that contain $\forall x \in X$ have been searched. Each vertex in $X$ are adjacent to every vertex in $R$ described below, or $X = \emptyset$.

$R$: $\forall r \in R$ links to each other, and $\Gamma(r) \cap X = X$.

$P$: $\forall p \in P$ links to all vertices in $R$, but $p \in P$ not necessarily links to each other. When vertex $p_1$ is deleted in $P$, set $\{ p \in P | p \neq p_1 \}$ is denoted as $\{ P \setminus p_1 \}$.

Status $s$ is defined as a combination of $X$, $R$, and $P$.

\begin{equation*}
\begin{split}
s &: \{ x \in X \}, \{ r \in R \}, \{ p \in P \} \\
\end{split}
\end{equation*}

### Raw Bron-Kerbosch's algorithm

*TODO*: B-K description is not accurate. 

Raw Bron-Kerbosch's algorithm could be expressed as:

* Step1: randomly select a vertex $p_1$ in $P$, then generate a new status $s_{new}$:

\begin{equation}
\begin{split}
s_{new} &: \{ \Gamma(p_1) \cap X \}, \{ r \in R, p_1 \}, \{ \Gamma(p_1) \cap P \} \\
\end{split}
(\#eq:1)
\end{equation}

$\{ \Gamma(p_1) \cap X \}$ means only vertices $x$ in $X$ adjacent to $p_1$ are kept. Because $X$ stores vertices that have been searched for maximal cliques, so the function of $x$ is to check if new cliques are part of searched ones. If $x$ is not adjacent to $p_1$, new cliques from $s_{new}$ are definitely not parts of already searched maximal cliques containing $x$. This assertion can be deducted from the definition of "clique" that every two distinct vertices in a clique are adjacent.

* Step2: iterate `Step1` until $P = \emptyset$:

\begin{equation*}
\begin{split}
s_{stop} &: \{ \Gamma(p_n) \cap \Gamma(p_{n-1}) \cap \dots \cap X \}, \{r \in R, p_1, \dots, p_n \}, \{ \} \\
\end{split}
\end{equation*}

which is denoted as:

\begin{equation*}
\begin{split}
s_{stop} &: \{ X_{stop} \}, \{ R_{stop} \}, \{ P_{stop} \} \\
\end{split}
\end{equation*}

Check if $X_{stop} = \emptyset$ in $s_{stop}$, which means there is no vertices in $X_{stop}$ adjacent to vertices in $R_{stop}$. If so, then $R_{stop}$ is a new maximal clique.

* Step3: backtrack to a updated status $s$:

\begin{equation}
\begin{split}
s_{updated} &: \{ x \in X, p_1 \}, \{ r \in R \}, \{ P \setminus p_1 \} \\
\end{split}
(\#eq:2)
\end{equation}

It means for status $s$, $p_1$ has been completely searched. Then, repeat `Step1` and `Step2` until all vertices in $P$ are searched, in another words, $P = \emptyset$, so we get all maximal cliques from status $s$.

The initial status of $G(V, E)$ could be set as:

\begin{equation*}
\begin{split}
s_{init} &: \{ \}, \{ \}, \{ v \in V \} \\
\end{split}
\end{equation*}

### LOVO

`LOVO` is designed based on the fact that: $\forall p \in P$ are searched in status $s$, and cliques in $s_{stop}$ is checked by $\Gamma(x)$. So for a given $x_i \in X$ if $P$ contains only $P \cap \Gamma(x_i)$, the status can be skipped.

The skippable status is described as, $\exists x_i$:

\begin{equation*}
\begin{split}
s_{skip} &: \{x \in X\}, \{  r \in R \}, \{ P \cap \Gamma(x_i | x_i \in X) = P \} \\
\end{split}
\end{equation*}

$P \cap \Gamma(x_i | x_i \in X)$ is equal to the number of skipped iterations.

In `LOVO`, $x_i$ is chosen to maximize $|N(x)|$:

\begin{equation*}
\begin{split}
N(x_i) &= P \cap \Gamma(x_i|x_i \in X) \\
\end{split}
\end{equation*}

The `LOVO` is described as:

* step1: select $x_i$ to maximize $|N(x)|$.

*Case1*: $P \setminus N(x_i) \neq \emptyset$, randomly select $p_1$ from $P \setminus N(x_i)$. In this way, $p \in  N(x_i)$ are always searched in last rank.

*Case2*: $P \setminus N(x_i) = \emptyset$, skip current status.

The status $s_{new}$ has the same format as \@ref(eq:1). Because $x_n \notin  \Gamma(p_1) \cap X$, the mode of $X$ is reduced in $s_{new}$. The status $s$ is updated as \@ref(eq:2).

* step2: use the same vertex selection and ordering method for $s_{new}$. Note that $x_i^{\prime}$ in $s_{update}$ may be different from the $x_i$ in $s$. It means $x_i$ is always chosen according to the current status $s$ and make the $|N(x_i)|$ local optimal. Repeat `step1` until $P = \emptyset$, then check whether current $R$ is a maximal clique.

* step3: backtrack to the second latest status, and repeat `step2` until no status left.

A search tree of status $s$ looks like:

```
{s}
{s_u, s_n} ## update s to s_u, generate s_n from s.
{s_u, s_u1, s_n1} ## update s_n to s_u1, generate s_n1 from s_n.
{s_u, s_u1, s_u2, s_n2}
{s_u, s_u1, s_u2, s_u3, s_n3} ## P in s_n3 is empty, check whether R in s_n is maximal clique.
{s_u, s_u1, s_u2, s_u3', s_n3'} ## update s_u3 to s_u3', generate s_n3' from s_u3.
{s_u, s_u1, s_u2, s_u3'} ## s_n3' is skipped because case3 above occurs.
...
{} ## Stop when no status left.
```

## Optimization

### Check before search

Different from Bron-Kerbosch's algorithm, `LOVO` "ordered" vertices in $P$ that roughly split $P$ into two groups $N(x_i)$ and $P \setminus N(x_i)$. Vertex $p$ for next search was randomly selected from $P \setminus N(x_i)$.

`LOVO` always checked whether current status is part of searched maximal cliques, so invalid iterations could be avoid. *Case2* in `step1` above described the condition, $P \setminus N(x_i) = \emptyset$. Besides, maximized $|N(x_i)|$ guaranteed that largest possible searched maximal cliques or parts were checked in high priority. 

It is possible that a chosen vertex $p_x$ from $P \setminus N(x_i)$ actually formed a searched maximal cliques. $p_x$ was selected just because its corresponding $N(x_j)$ is not maximal. Any $p_x$ like below should be omitted:

\begin{equation*}
\begin{split}
\{ \Gamma(p_x) \cap P, p_x \} \subset \Gamma(x_j | x_j \in X) \\
\end{split}
\end{equation*}

`LOVO` only did one more search for $p_x$. Because when $p_x$ was selected, new status would be:

\begin{equation*}
\begin{split}
s_{new} &: \{ \Gamma(p_x) \cap X \}, \{ r \in R, p_x \}, \{ \Gamma(p_x) \cap P \} \\
\end{split}
\end{equation*}

Because $p_x$ and $x_j$ are adjacent, $x_j \in \Gamma(p_x) \cap X$. Then $x_j$ would be chosen in $s_{new}$, so $s_{new}$ would be skipped before next search.


### Quick backtracking when $P = \emptyset$

When $P = \emptyset$ in status $s$, a clique $R$ appeared. A continuously changed $P$ and $R$ may occur in continuous status. Then multiple status could be skipped at once in backtracking. For example:

```
{s_u, s_u1, s_u2, s_u3, s_n3}
s_n3: R is {R, p1, p2, p3}, P is empty
s_u3: R is {R, p1, p2}, P is {p3}
s_u2: R is {R, p1}, P is {p2, p3}
s_u1: R is {R}, P is {p1, p2, p3}
```

Status \{ $s_x | x \in \{last-1, last-2, last-3, ...\} \}$ were immediately skipped in `LOVO`, when:

\begin{equation*}
\begin{split}
|R_x| + |P_x| <& |R_{last}| \\
P_{last} &= \emptyset
\end{split}
\end{equation*}

### `bitset` transformation of linked vertices

Compared to Bron-Kerbosch's algorithm, `LOVO` added the step $N(x_n)$ that handled huge amount of `set intersection` and `set union` operation. Instead of holding a integer vector for vertex indices, `LOVO` implemented a `bitset` for edge representation. A similar strategy called `bitscan` is used[@san2018efficiently].

For example, using integer vector a triangle graph is represented as:

```
0: 1, 2
1: 0, 2
2: 0, 1
```

In `LOVO`, the graph is transformed as:

```
110
101
011
```

`LOVO`, even the operation $\Gamma(p_1) \cap P$ in Bron-Kerbosch's algorithm, benefited greatly from bit `and` and `or` with hardware optimization in different languages. Moreover, `bitset` used much less memory compared to integer vector. For the example above, integer vector needed at least $N \times 6$ bits where $N$ is usually 32 or 64, while `bitset` used 9 bits. 

# Discussion 

## Set $X$ in Bron-Kerbosch's algorithm

Interestingly, as described in Bron-Kerbosch's algorithm, for a given status $s$, $\forall r \in R$ $X \cap \Gamma(r) = X \mathrm{or} \: \emptyset$. It means each vertex in $X$ is adjacent to every vertex in $R$, unless $X = \emptyset$. We denote $X \cap \Gamma(r)$ as $N(r)$.

Proof:

If

\begin{equation*}
\begin{split}
s &: \{x_1 \}, \{ \}, \{ p \in P \} \\
\end{split}
\end{equation*}

then

\begin{equation*}
\begin{split}
s_{next} &: \{\Gamma(p_1) \cap x_1 \}, \{ p_1 \}, \{ \Gamma(p_1) \cap P \} \\
\end{split}
\end{equation*}

and 

\begin{equation*}
\begin{split}
s_{update} &: \{x_1, p_1 \}, \{  \}, \{ P \setminus p_1 \} \\
\end{split}
\end{equation*}

For $s_{next}$ above, if $\Gamma(p_1) \cap x_1 = \emptyset$, then $N(r) = \emptyset$. Or if $\Gamma(p_1) \cap x_1 = x_1$, it means $x_1$ is adjacent to $p_1$, then $N(r) = x_1$. For the $s_{update}$ above, $N(r) = \emptyset$, so as $s$.

If the assertion above holds for status $s^{\prime}$:

\begin{equation*}
\begin{split}
s^{\prime} &: \{ \Gamma(p_1) \cap \dots \cap \Gamma(p_n) \cap X \}, \{r \in R, p_1, \dots, p_n \}, \{ P \setminus \{ p_1, \dots, p_n \} \} \\
\end{split}
\end{equation*}

which is also denoted as:

\begin{equation*}
\begin{split}
s^{\prime} &: \{ X^{\prime} \}, \{ R^{\prime} \}, \{ P^{\prime} \}
\end{split}
\end{equation*}

then

\begin{equation*}
\begin{split}
s^{\prime}_{next} &: \{ \Gamma(p_{n+1}) \cap X^{\prime} \}, \{R^{\prime}, p_{n+1} \}, \{ \Gamma(p_{n+1}) \cap P^{\prime} \} \\
\end{split}
\end{equation*}

and 

\begin{equation*}
\begin{split}
s^{\prime}_{update} &: \{X^{\prime}, p_{n+1}\}, \{ R^{\prime} \}, \{ P^{\prime} \setminus p_{n+1} \} \\
\end{split}
\end{equation*}

For $s^{\prime}_{next}$ above, if $\Gamma(p_{n+1}) \cap X^{\prime} = \emptyset$, then $N(r) = \emptyset$. If not, because every vertex in $X^{\prime}$ are adjacent to each vertex in $R^{\prime}$ in $s^{\prime}$, $\Gamma(p_{n+1}) \cap X^{\prime}$ means only vertices adjacent to $p_{n+1}$ are kept in $X^{\prime}$, then $N(r) = X$ holds. For $s^{\prime}_{update}$ above, because $p_{n+1}$ is adjacent to every vertex in $R^{\prime}$, then $N(r) = X$ holds.


# Unsolved problems

## Vertices ordering in $P$

**Strategy 1**: choose $v \in P$ that maximizes $\Gamma(v) \cap P$, then $v$ will be move to $X$ in the next status $s$. The search number will be reduced.

# References
